### ISSUE TITLE
NM_CONTROLLED line not there by default, needed updated instructions for AD.

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq_docs#10]
With NetworkManager disabled, the NM_CONTROLLED line is not longer there in eth0, need to update the active_directory.adoc sed line accordingly.

**Comment by chessbyte** [comment]
@abellotti is this still an issue that needs to be addressed?

**Comment by abellotti** [comment]
wow, that issue goes back a few years (CentOS 6/7) 😁 yep, still an issue, I will create a PR.

**Comment by abellotti** [comment]
Resolved by: https://github.com/ManageIQ/manageiq_docs/pull/1408
