### ISSUE TITLE
Missing high availability documentation when building

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq_docs#1101]
Original issue https://github.com/ManageIQ/manageiq.org/issues/664

When running `asciidoctor`, the high availability isn't build into the result. Just guessing that the issue is around the topic map file and we might also miss other documentation parts.

This is causing the website not to have these docs :disappointed:

**Comment by Fryguy** [comment]
Closed via https://github.com/ManageIQ/manageiq.org/pull/828
