### ISSUE TITLE
"Obtaining the Appliance" section needs updates

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq_docs#1271]
User Reference -> Installation -> Microsoft Azure (or Openstack/RHV), section 1.1

1. "navigate to [manageiq.org/download](http://manageiq.org/docs/reference/latest/doc-Installing_on_Microsoft_Azure/miq/manageiq.org/download)" link is broken.

1. step 2 to 4 talk about choosing platform/release from list and follow instruction, but we no longer use dropdown lists in the download page.

**Comment by chessbyte** [comment]
@simaishi The broken links are fixed with this [PR](https://github.com/ManageIQ/manageiq_docs/pull/1402).

Any suggestions for new wording on steps 2-4?

**Comment by simaishi** [comment]
I think the download page is simple enough that we can probably just say download an appropriate image?
