### ISSUE TITLE
VM management missing retirement info

### ISSUE THREAD

**Issue by d-m-u** [ManageIQ/manageiq_docs#1349]
Arghhh I don't have time to fix this right now but the vm management should include retirement:
<img width="813" alt="Screen Shot 2020-02-20 at 11 32 10 AM" src="https://user-images.githubusercontent.com/16326669/74956843-bd296400-53d4-11ea-9b58-e42e07cb8b18.png">
 
and should be using the new call, for RAAR

**Comment by chessbyte** [comment]
@d-m-u was this completely addressed by #1351 or are more PRs needed to fix this?

**Comment by d-m-u** [comment]
I think there's a few more that need to be addressed: 
 manageiq_docs/api/reference/service_custom_actions.adoc 
api/examples/custom_action_service.adoc
api/overview/json.adoc
methods_available_for_automation/Methods_Available_for_Automation.adoc

**Comment by d-m-u** [comment]
Sorry, just kidding, I was looking at the other issue, this can be closed.
