### ISSUE TITLE
still using old retirement calls in the following files

### ISSUE THREAD

**Issue by d-m-u** [ManageIQ/manageiq_docs#1358]
As of when this was opened, I think we're using the wrong call in at least the following places still:
I'll fix them as time allows. It's worth noting these changes should all go back to h and i. 

https://github.com/ManageIQ/manageiq_docs/blob/39503bb22c58e413b42da6c056167c2166cd389b/api/reference/service_custom_actions.adoc#L338

https://github.com/ManageIQ/manageiq_docs/blob/abdf3b617f9f1233f76dfd877271cb71052aa001/api/overview/json.adoc#L250

https://github.com/ManageIQ/manageiq_docs/blob/ca32417489b7aa768e73cdeeb79b41d1548a6ddb/api/reference/services.adoc#L666

**Comment by chessbyte** [comment]
@d-m-u what should those be changed to?

**Comment by d-m-u** [comment]
The updated API endpoint as of the last three versions is  `request_retire`, not `retire`, getting to it today.

**Comment by d-m-u** [comment]
https://github.com/ManageIQ/manageiq_docs/pull/1406
https://github.com/ManageIQ/manageiq_docs/pull/1405

**Comment by chessbyte** [comment]
@d-m-u @abellotti Now that #1405 and #1406 have been merged, can this issue be closed?

**Comment by abellotti** [comment]
I still see one in api/examples/custom_action_service.adoc, I'll take care of it.

**Comment by abellotti** [comment]
https://github.com/ManageIQ/manageiq_docs/pull/1410

**Comment by chessbyte** [comment]
@abellotti Now that #1405, #1406 and #1410 have been merged, can this issue be closed?

**Comment by abellotti** [comment]
Yep 👍
