### ISSUE TITLE
no documentation for arbitration_profiles, arbitration_settings, arbitration_rules REST API

### ISSUE THREAD

**Issue by mkoura** [ManageIQ/manageiq_docs#195]
REST API for arbitration_profiles, arbitration_settings and arbitration_rules is not documented.

**Comment by abellotti** [comment]
The API endpoints for
- arbitration_profiles
- arbitration_settings
- arbitration_rules

were removed from the API for v3.0.0 of the API by https://github.com/ManageIQ/manageiq/pull/14776 so they were not there in Gaprindashvili.

Closing this Issue.
