### ISSUE TITLE
Document that Openstack provider user must have admin role

### ISSUE THREAD

**Issue by aufi** [ManageIQ/manageiq_docs#201]
We need document, that user which is used in Openstack provider setup must have an admin role for his domain. Otherwise it causes various issues including failed refresh.

Multiple Openstack domains are supported since #9222 was merged.

This doc issue was moved from https://github.com/ManageIQ/manageiq/issues/12860

**Comment by Fryguy** [comment]
@adahms. Please review.  Apparently this is causing a number of support tickets, so we'd like this in as soon as possible.

**Comment by adahms** [comment]
@aufi @Fryguy 

Thank you for raising this issue.

I have now submitted #225 , which re-words the note about the required permissions for users to be a little more specific.

Does this provide sufficient information?

**Comment by aufi** [comment]
@adahms Thanks for the PR, commented there.. (words are ok, but it should be moved under OSP Cloud provider)

**Comment by adahms** [comment]
@aufi Thanks for taking a look - I have now moved that line over to the cloud provider section, and have converted it into an 'Important' box to provide more context.

**Comment by aufi** [comment]
@adahms Thanks, current state of #225 PR looks good to me!

**Comment by aufi** [comment]
https://github.com/ManageIQ/manageiq_docs/pull/225 was merged, closing this issue.
