### ISSUE TITLE
outdated documentation for Creating Chargeback Rates

### ISSUE THREAD

**Issue by mkoura** [ManageIQ/manageiq_docs#238]
http://manageiq.org/docs/reference/latest/api/reference/chargebacks_rates#creating-rates
The request described in doc fails with
```
{
  "error": {
    "kind": "bad_request",
    "message": "Chargeable field can't be blank",
    "klass": "Api::BadRequestError"
  }
}
```
In current version also "chargeable_field_id" needs to be specified.

**Comment by chessbyte** [comment]
@abellotti Is this old issue still valid?

**Comment by abellotti** [comment]
yep, still an issue.
