### ISSUE TITLE
The TLS/SSL verify_peer setting is about to change

### ISSUE THREAD

**Issue by blomquisg** [ManageIQ/manageiq_docs#244]
See https://github.com/ManageIQ/manageiq/pull/14019 and https://github.com/ManageIQ/manageiq/pull/14004

The situation is that there was a setting for whether or not to verify the peer certificate when connecting to Container or RHV providers.  When `verify_ssl` was set to `1` (meaning, `true`) it wasn't actually verifying the peer certificate.

Additionally, the default was to set `verify_ssl` to `1`.

The fix being put in place will start enforcing the `verify_ssl` setting.  However, it's impossible to know whether the existing value for `verify_ssl` is correct or not.

The documentation need is to explain that there are two possible outcomes:

1. The user has a valid SSL certificate for their provider and it is signed by a trusted CA (e.g. Verisign).  In which case, the user will notice no changes and will need to take no action.

2.  The user has a self-signed SSL certificate for their provider.  In which case, either the Schedule Worker or an attempt to collect inventory will render the provider connection invalid:

![image](https://cloud.githubusercontent.com/assets/14183/23475396/77382866-fe85-11e6-99e9-6bb6b277a10d.png)

In this situation, the user has two options:

A) Configure a custom CA to trust:

![image](https://cloud.githubusercontent.com/assets/14183/23475506/cc7bfa28-fe85-11e6-834b-b950aad359dc.png)

B) Disable the certificate validation.

**Comment by cben** [comment]
See also the UI PR https://github.com/ManageIQ/manageiq-ui-classic/pull/450 for more screenshots.

**Comment by cben** [comment]
Doc BZ https://bugzilla.redhat.com/show_bug.cgi?id=1432260

**Comment by cben** [comment]
cc @dayleparker @adahms these changes also affected RHV & Middleware providers  — are there similar efforts to update those docs?
- Containers & RHV started enforcing previously insecure SSL, which may break existing providers until edited.
- Middleware didn't support HTTPS, so nothing broke, just new options.

https://github.com/ManageIQ/manageiq-ui-classic/pull/759 also moved "Security Protocol"  field above hostname, port for several providers whose SSL support didn't change.  That PR may be helpful as overview — has screenshots of I believe final look of all affected providers.

**Comment by adahms** [comment]
@cben - Yes, we have bugs to track the changes required for RHV and Middleware providers here -

**Hawkular**
https://bugzilla.redhat.com/show_bug.cgi?id=1437286

**RHV**
https://bugzilla.redhat.com/show_bug.cgi?id=1431869

Thank you for letting us know about the updates - I understand we may need to raise a few more bugs to ensure all changes are updated, and will review #759 for changes as well.

Feel free to let us know at any stage if there are any specific details you feel we should add!

**Comment by dayleparker** [comment]
@cben, thanks for all the details, it's very helpful. 

BTW, we have a new bug now for the OpenShift/RHV SSL updates so as to not hold up the other updated parts of the procedures -- I've added you to the CC list: https://bugzilla.redhat.com/show_bug.cgi?id=1440602

**Comment by dayleparker** [comment]
Hi @cben and @blomquisg,
We need to link to a downstream bug to publish a Known Issue in the Release Notes (Our RNs bug: https://bugzilla.redhat.com/show_bug.cgi?id=1444325).
Can you please link me to the related engineering bug? I've searched and unfortunately haven't had any luck finding this particular one. 
Thank you for your help,
Dayle

**Comment by cben** [comment]
perhaps https://bugzilla.redhat.com/show_bug.cgi?id=1429891 "[RFE] Support SSL with Validation (CA) for OpenShift Provider"
@jhernand @josejulio did you have any BZ for oVirt / Middleware SSL?

**Comment by josejulio** [comment]
I had this JIRA: https://issues.jboss.org/browse/HAWKULAR-1199

**Comment by dayleparker** [comment]
Thanks @cben and @josejulio.
I've tied this known issue in the RNs to BZ#1429891, and have updated the Gitlab repo now. 
@adahms, do we need to create doc text, or attach any flags/keywords to the bug to make it an official 'known issue'?

**Comment by cben** [comment]
I think this has long been documented and can be closed.
