### ISSUE TITLE
Document how to install Ansible on ManageIQ Appliance

### ISSUE THREAD

**Issue by mfeifer** [ManageIQ/manageiq_docs#323]
While Ansible features can be used on the ManageIQ Appliance, it is not installed by default on the appliance.  This procedure must be documented.

Requesting subject matter expert and writer.

**Comment by mfeifer** [comment]
@adahms see above 
@gtanzillo please assign a subject matter expert

**Comment by mfeifer** [comment]
@carbonin GreggT asked me to assign you to this.

**Comment by carbonin** [comment]
I think http://talk.manageiq.org/t/howto-setup-embedded-ansible/2291/2 should be able to help with this documentation.

**Comment by chessbyte** [comment]
Now that we use Ansible Runner for embedded Ansible, I believe this can be closed.
