### ISSUE TITLE
Broken RHEV link

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq_docs#366]
From http://manageiq.org/docs/reference/
following link is broken.
http://manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Enterprise_Virtualization/miq

**Comment by alejojo** [comment]
I just came to say this haha!

**Comment by FlorianOnmyown** [comment]
From what I can see, this issue has been solved.

**Comment by tjyang** [comment]
Yes, thanks for the fix to whoever fix it.
