### ISSUE TITLE
Document One-cloud-provider per OpenStack-domain

### ISSUE THREAD

**Issue by aufi** [ManageIQ/manageiq_docs#402]
There are some users don't who understand, that MIQ doesn't autodetect domains for given Openstack user. Change on source code level would require huge changes in modelling. So we should document it better at least for now.

We need add the information [1] into (or close to) adding Cloud providers chapter [2].

[1] Something like: ```The provider you're creating will be able to see inventory from the given domain only. If you want see other domain inventory, add it as other Cloud provider```
[2] 4.1.1. Adding OpenStack Providers, a bullet 5 Select the appropriate API Version... http://manageiq.org/docs/reference/latest/doc-Managing_Providers/miq/#openstack-providers

**Comment by aufi** [comment]
@tzumainn @cbudz  Hi, could we get a guidance how to make this change into docs?

**Comment by adahms** [comment]
@aufi - Thanks for following up on this issue, and my apologies that we had not triaged this one yet.

Now assigning to Suyog for review.

@suyogsainkar - could you work with Marek to get this change in the docs?

**Comment by suyogsainkar** [comment]
@adahms Sure, thanks.

@aufi I've added a note to that effect in the Adding OpenStack Providers section via https://github.com/ManageIQ/manageiq_docs/pull/432. Would you mind taking a look at the addition? Please let me know if you think it needs any correction. Thanks! -Suyog

**Comment by aufi** [comment]
@suyogsainkar Thanks for the PR, I commented there.

**Comment by suyogsainkar** [comment]
@aufi Many thanks for your review and suggestion. I've made that change and merged it to master. Thanks!
