### ISSUE TITLE
"Configuring Automatic Tagging for Container Entities" missing from http://manageiq.org/docs

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq_docs#507]
This chapter:
https://github.com/ManageIQ/manageiq_docs/blob/master/doc-Managing_Infrastructure_and_Inventory/topics/Container_Entities.adoc
seems to be missing from on http://manageiq.org/docs/reference/latest/doc-Managing_Infrastructure_and_Inventory/miq/
It does exist [downstream](https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.5/html/managing_infrastructure_and_inventory/container_entities).

**Comment by FlorianOnmyown** [comment]
The chapter https://github.com/ManageIQ/manageiq_docs/blob/master/doc-Managing_Infrastructure_and_Inventory/topics/Data_Optimization_Features.adoc is also missing.

Even if the 2 topics are well listed in https://github.com/ManageIQ/manageiq_docs/blob/master/doc-Managing_Infrastructure_and_Inventory/cfme/master.adoc

**Comment by cben** [comment]
Thanks @FlorianOnmyown your mention of `cfme/master.adoc` put me on the right track to solve it myself — turns out these 2 were missing from the separate `miq/index.adoc` => fixing in #587.
