### ISSUE TITLE
v2.2.0 of API documentation is no longer visible

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq_docs#63]
With latest commit, v2.2.0 of the API documentation (upstream/cf 4.1) - no longer visible from the built asciibinder left table of content.

**Comment by adahms** [comment]
Hi Alberto,

See - https://github.com/ManageIQ/manageiq_docs/pull/65

**Comment by adahms** [comment]
The pull request in the above comment has now been merged; closing.
