### ISSUE TITLE
Installing MIQ on Google Compute Engine - simplification

### ISSUE THREAD

**Issue by kuklis** [ManageIQ/manageiq_docs#656]
There is no need to download and upload the storage file as it is already stored in Google Storage as public. Steps in 1.1 and 1.2.3-1.2.5 are unnecessary. Instead you can jump to creating the image, just provide the bucket and storage file name in "Cloud Storage File" field, ie:
manageiq/gaprindashvili-1-rc1.tar.gz
See https://cloud.google.com/compute/docs/instances/create-start-instance#publicimage

![creating an instance from a public image](https://user-images.githubusercontent.com/14141591/34844708-b1cdb5e6-f712-11e7-990a-7f458da0d2b0.jpg)

**Comment by simaishi** [comment]
We're no longer uploading GCE images. Rather than changing this doc, we'll need to update Get Started doc so we don't instruct users to use pre-published images (https://github.com/ManageIQ/manageiq.org/issues/794)
