### ISSUE TITLE
Local preview does'nt look like manageiq website

### ISSUE THREAD

**Issue by gaurav-nelson** [ManageIQ/manageiq_docs#833]
By following the commands in README, I was able to build the docs, but final output looks like this:
![image](https://user-images.githubusercontent.com/23069445/39907127-fc2689ea-5529-11e8-978d-75e606e89781.png)

This is nothing like http://manageiq.org/docs/ site.

**Comment by chessbyte** [comment]
in order to make it look like website locally, one has to follow steps in https://github.com/ManageIQ/manageiq.org/blob/master/README.md
