### ISSUE TITLE
Document setting up custom SSL certificates on an appliance 

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq_docs#974]
Credit goes to @naltun for writing up and testing out the following steps:

How to get new certs running on ManageIQ.
1) Download any validation files, and upload them to the server. You can do this by:
$ scp $my_file user@$ip_address:/path/to/location/
2) Validate your domain through your certificate authority
3) Download your certificates, and upload them to the server
Can be done by using scp $my_file user@$ip_address:/path/to/location/
4) Your files may be using the .cer or the .crt extensions. Both work. However, you'll need to
change the names of the files. ManageIQ uses server.cer and server.cer.key. These files
can be found in /var/www/miq/vmdb/certs. Go into that directory, and ls. You'll see
those two files. Now take your certificate and certificate key files and rename them;
the certificate should be renamed to server.cer, and the key file to server.cer.key.
If you are unsure which file is the certificate, and which is the key, then `cat' server.cer
and server.cer.key, and compare the files to your files.
5) After you've replaced the files in /var/www/miq/vmdb/certs/, go back one directory (/var/www/miq/vmdb/)
and run bundle exec rake evm:restart. Your certs should be active and you should be
connected over HTTPS.

---

Also opened as https://bugzilla.redhat.com/show_bug.cgi?id=1632947

**Comment by Fryguy** [comment]
Note that most of this seems possibly already covered in
- https://github.com/ManageIQ/manageiq_docs/blob/69a415196db3a0cb8051135a6b4f4d2acef852e3/doc-Appliance_Hardening_Guide/topics/SSL_Certs.adoc
- https://github.com/ManageIQ/manageiq_docs/blob/69a415196db3a0cb8051135a6b4f4d2acef852e3/doc-Appliance_Hardening_Guide/topics/DB_SSL.adoc

but that hardening guide is not available to the https://manageiq.org/docs build, and thus no one knows about it.

**Comment by chessbyte** [comment]
@Fryguy Now that the hardening guide is available [here](https://www.manageiq.org/docs/reference/latest/doc-Appliance_Hardening_Guide/miq/), can this issue be closed?

**Comment by Fryguy** [comment]
Yes, thanks!
