### ISSUE TITLE
incomplete documentation for /api/groups — filters

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq_docs#977]
https://github.com/ManageIQ/manageiq_docs/blob/master/api/reference/groups.adoc
```
    "filters" : {
      "belongsto" : [ "/managed/area/1", "/managed/area/2", "/managed/area/3" ],
      "managed" : [[ "/managed/infra/1", "/managed/infra/2"], ["/managed/other/3"]]
    }
```
This shows the structure (belongsto is flat, managed is grouped by tag category) but doesn't explain at all what these filters *mean*.

Corresponding UI seems to be documented here:
https://github.com/ManageIQ/manageiq_docs/blob/master/doc-General_Configuration/topics/Configuration.adoc#groups
https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.6/html/general_configuration/configuration#groups
but it's unclear how that maps to the API.

> Limit what users in this group can view by selecting filters in the Assign Filters** area.

Does this reflect in `filters.belongsto` or `filters.managed` (or both)?
Does the nested structure of `filters.managed` reflect something like "AND by category, OR within category"?

> - Select **Tags Based On Expression**, then create tags based on an expression using AND, OR, or NOT. This allows you to further limit the resources accessible to a user: for example, to specify a combination of tags that must exist on a resource.

How is this mode reflected in API?

(Source code is doesn't make these obvious either, especially since "groups" are involved with "entitlements" since https://github.com/ManageIQ/manageiq/pull/8102 ...)

**Comment by abellotti** [comment]
As I've been investigating the doc update, I stumbled on a gap with the UI re: filter expressions.

- [ ] Add support for filter_expression, i.e. Tags Based on Expression - https://github.com/ManageIQ/manageiq-api/pull/806
- [ ] Enhance documentation
